export const JOB_ROLES = [
    "ACES manager",
    "Area Manager",
    "Area Manager GSF delivery",
    "Change ops",
    "Channel Team Lead",
    "CTL-Quick Commerce Last Mile",
    "FCD Area manager",
    "HK Sup.",
    "HR Associate Partner",
    "HRBP",
    "IB Area Manager",
    "ICQA Manager",
    "ICQA RA",
    "IT",
    "IT Manager",
    "IT Support",
    "IT Support Associate II",
    "MST",
    "OB Area Manager",
    "Operations Manager",
    "Ops Manager",
    "OPS Manager II",
    "OPS Manager III",
    "Process Assistant",
    "PXT Co-ordinator",
    "Regional WHS Manager",
    "RME Coordinator",
    "RME Manager",
    "Site Lead",
    "Site Lead- Amazon Fresh",
    "Site Leader",
    "SLP Co-Ordinator",
    "SLP Coordinator",
    "SLP Manager",
    "SLP Specialist",
    "Sr HR Business Partner",
    "Team Lead",
    "Team Lead, Fresh Delivery",
    "Team Lead-Line Haul",
    "Team Lead-UFF/SSD FC",
    "Team Leader - Spoke",
    "Trainer, GSF L&D",
    "WHS Manager",
    "WHS Officer",
    "WHS Supervisor"
];
